// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7d6ad50cDecodeGithubComFlutterDizasterMusicLibraryInternalModels(in *jlexer.Lexer, out *SongTitle) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "group":
			out.Group = string(in.String())
		case "song":
			out.Song = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7d6ad50cEncodeGithubComFlutterDizasterMusicLibraryInternalModels(out *jwriter.Writer, in SongTitle) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"group\":"
		out.RawString(prefix[1:])
		out.String(string(in.Group))
	}
	{
		const prefix string = ",\"song\":"
		out.RawString(prefix)
		out.String(string(in.Song))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SongTitle) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7d6ad50cEncodeGithubComFlutterDizasterMusicLibraryInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SongTitle) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7d6ad50cEncodeGithubComFlutterDizasterMusicLibraryInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SongTitle) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7d6ad50cDecodeGithubComFlutterDizasterMusicLibraryInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SongTitle) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7d6ad50cDecodeGithubComFlutterDizasterMusicLibraryInternalModels(l, v)
}
